services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080" # Dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ttm_front

  app:
    image: imagebackttm
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ttm
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/ttm
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`back.localhost`)"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
    networks:
      - db
      - ttm_front

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ttm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - backttm_data:/var/libs/postgresql/data
    networks:
      - db
      - ttm_front

volumes:
  backttm_data:
networks:
  db:
  ttm_front:
    external: true

