services:
  app:
    image: imagebackttm
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ttm
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/ttm
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy


    networks:
      - db

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ttm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - backttm_data:/var/libs/postgresql/data
    networks:
      - db

volumes:
  backttm_data:

networks:
  db:

