spring:
  application:
    name: trouve ton match
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm
    username: postgres
    password: postgres
  liquibase:
    driver-class-name: org.postgresql.Driver
    drop-first: false
    enabled: true
    url: jdbc:postgresql://localhost:5432/ttm
    user: postgres
    password: postgres
    change-log: classpath:/db/changelog/db.changelog-master.sql
  data:
    mongodb:
      database: ttm
      host: localhost
      port: 27017

security:
  jwt:
    token:
      secret-key: 7cdbb7e18fa7ccc4cf1ded401aad9d350a66f123d38f377a58e8767fe70ee677
      expiration-milliseconds: 604800000

#  mongo:
#    url: mongodb://localhost:27017/?replicaSet=rs0
#    db: ttm
